// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQJZuPnJffQ6e8Lw76K1lbuQUZWfZk8Q',
    appId: '1:826624660598:web:ffb3ce7575595839b63b57',
    messagingSenderId: '826624660598',
    projectId: 'baskit-b54b5',
    authDomain: 'baskit-b54b5.firebaseapp.com',
    storageBucket: 'baskit-b54b5.firebasestorage.app',
    measurementId: 'G-WJ3Y9RW91K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhMdjrPtixbtjJZ2pzk0abkVC7k50MJ94',
    appId: '1:826624660598:android:585ded1dbdb34736b63b57',
    messagingSenderId: '826624660598',
    projectId: 'baskit-b54b5',
    storageBucket: 'baskit-b54b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqVepUdpztFTYExCiodu1aXCyrfukhc8',
    appId: '1:826624660598:ios:fbbea3b5e3b91e15b63b57',
    messagingSenderId: '826624660598',
    projectId: 'baskit-b54b5',
    storageBucket: 'baskit-b54b5.firebasestorage.app',
    androidClientId: '826624660598-ce39rdd160u2ipc0ld3vksoi62h1i75h.apps.googleusercontent.com',
    iosClientId: '826624660598-5k4krhqovu5pp4gcbldpilb5beudmt7e.apps.googleusercontent.com',
    iosBundleId: 'com.cboxlab.baskit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXqVepUdpztFTYExCiodu1aXCyrfukhc8',
    appId: '1:826624660598:ios:fbbea3b5e3b91e15b63b57',
    messagingSenderId: '826624660598',
    projectId: 'baskit-b54b5',
    storageBucket: 'baskit-b54b5.firebasestorage.app',
    androidClientId: '826624660598-ce39rdd160u2ipc0ld3vksoi62h1i75h.apps.googleusercontent.com',
    iosClientId: '826624660598-5k4krhqovu5pp4gcbldpilb5beudmt7e.apps.googleusercontent.com',
    iosBundleId: 'com.cboxlab.baskit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQJZuPnJffQ6e8Lw76K1lbuQUZWfZk8Q',
    appId: '1:826624660598:web:c1c5e9c0f81f7536b63b57',
    messagingSenderId: '826624660598',
    projectId: 'baskit-b54b5',
    authDomain: 'baskit-b54b5.firebaseapp.com',
    storageBucket: 'baskit-b54b5.firebasestorage.app',
    measurementId: 'G-9QGLWX6FDJ',
  );
}
