services:
  # backend development container
  backend-shell:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-100}
    container_name: baskit-backend-shell
    volumes:
      - ./backend:/workspace:rw
    environment:
      - WRANGLER_SEND_METRICS=false
    working_dir: /workspace
    ports:
      - "8787:8787"
    command: tail -f /dev/null
    stdin_open: true
    tty: true